#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED

#define ID_ICON 1001
#define ID_CURSOR 1002
#define IDR_MYMENU 101
#define ID_START 102
#define ID_STOP 103

#endif // RESOURCE_H_INCLUDED
