//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeroplane
    {
        public Aeroplane()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int id { get; set; }
        public int flightid { get; set; }
        public int capacity { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
