//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.baggage = new HashSet<baggage>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<baggage> baggage { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
