//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.Aeroplane = new HashSet<Aeroplane>();
        }
    
        public int id { get; set; }
        public int cost { get; set; }
        public int departingpointid { get; set; }
        public int arrivalpointid { get; set; }
    
        public virtual ICollection<Aeroplane> Aeroplane { get; set; }
        public virtual Station Station { get; set; }
    }
}
