//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public System.DateTime departingtime { get; set; }
        public System.DateTime arrivaltime { get; set; }
        public string name { get; set; }
        public string country { get; set; }
        public int id { get; set; }
    
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
