//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int aeroplaneid { get; set; }
        public int ownerid { get; set; }
        public int flightid { get; set; }
        public int cost { get; set; }
        public int id { get; set; }
        public int seat { get; set; }
    
        public virtual Aeroplane Aeroplane { get; set; }
        public virtual Client Client { get; set; }
    }
}
