#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED

#define ID_ADDBUTTON 100
#define ID_CLEARBUTTON 101
#define ID_TORIGHTBUTTON 102
#define ID_DELETEBUTTON 103
#define ID_EDIT 104
#define ID_FIRSTTBOX 105
#define ID_SECONDBOX 106

#endif // RESOURCE_H_INCLUDED
